# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem 'rspec', "~> 3.1.0"
gem 'byebug'
gem 'pry'
gem 'activesupport'
